### ISSUE TITLE
Eureka is not registering my API-GATEWAY instance

### ISSUE THREAD

**Issue by Kordedekehine** [shabbirdwd53/Springboot-Microservice#14]
It only identifies the user and department service. See it here

![image](https://user-images.githubusercontent.com/84699953/212647944-6805b05f-758b-4087-92b1-38856c4ca0de.png)

**Comment by suyash172003** [comment]
I’m interested in solving this. Could you assign it to me?

**Comment by Kordedekehine** [comment]
What's funny about this is that I've totally forgotten I put up such an issue. If you're interested, please feel free to contribute. Happy Coding!

**Comment by suyash172003** [comment]
Hi @Kordedekehine,
I tested this issue in my local setup, and I found that all services are showing properly in Eureka without any changes made. It seems that the issue might be environment-specific, so I suggest checking the configuration or environment settings in the affected environment (e.g., staging or production). Let me know if you need further assistance with this.

![Screenshot 2024-11-11 161018](https://github.com/user-attachments/assets/6007498c-8803-4a56-a8fd-bf8910015047)

**Comment by Kordedekehine** [comment]
Yes I later sorted the issue then. It was environment specific

**Comment by Kordedekehine** [comment]
Thank you @suyash172003
